### ISSUE TITLE
make install 时出错

### ISSUE THREAD

**Issue by zhuanqizhirou** [Qquanwei/emacs#4]
新装的Ubuntu 18,linux新手，
makefile:13: *** 遗漏分隔符 (null)。 停止。
请问是什么原因？

**Comment by Qquanwei** [comment]
好的，稍后我会看一下。
最新的配置不运行make也可以执行的。

git clone https://github.com/Qquanwei/emacs.git .emacs.d/
启动emacs即可

**Comment by zhuanqizhirou** [comment]
非常感谢，原来还有把配置文件写进org的用法。有没有QQ可否加一下？

**Comment by Qquanwei** [comment]
1158607740

来呀或者去这里讨论 https://emacs-china.org/ 
:)
