### ISSUE TITLE
makefile无法执行

### ISSUE THREAD

**Issue by whickorwell** [Qquanwei/emacs#5]
当我初次make install时，提示：
makefile:13: *** missing separator.  Stop.
我把所有空格改为tab后显示：
/bin/bash: pip: command not found
/bin/bash: brew: command not found
make: *** [makefile:13: install] Error 127
迫不得已转为txt格式：
[makefile.txt](https://github.com/Qquanwei/emacs/files/5113616/makefile.txt)

**Comment by Qquanwei** [comment]
其实不用make也可以执行，需要的命令在使用的时候才会提示不存在，对于大部分功能不影响

**Comment by Qquanwei** [comment]
我修复了下，把空格改成了tab，目前makefile还只针对macos，需要对linux进行优化。
